---
abstract: 'Tags helper for definition list.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  CSS::Struct::Output::Structure: 0
  English: 0
  Error::Pure::Utils: 0
  ExtUtils::MakeMaker: 6.36
  Tags::HTML::DefinitionList: 0
  Tags::Output::Structure: 0
  Test::MockObject: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tags-HTML-DefinitionList
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Utils: 0.02
  Error::Pure: 0.07
  Mo::utils::CSS: 0.06
  Tags::HTML: 0.08
  perl: 5.8.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/Tags-HTML-DefinitionList/issues
  homepage: https://github.com/michal-josef-spacek/Tags-HTML-DefinitionList
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Tags-HTML-DefinitionList
version: '0.02'
